"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const core=require("../lib/core");
const {pickBest,normalizeYtdlp,raceProviders}=require("../api/extract");
const download=require("../api/download");
test("classifies supported URL kinds",()=>{assert.equal(core.classifyUrl("https://www.instagram.com/stories/demo/1/").kind,"story");assert.equal(core.classifyUrl("https://www.facebook.com/story.php?story_fbid=1&id=2").kind,"story");assert.equal(core.classifyUrl("https://www.tiktok.com/@demo").kind,"profile");assert.equal(core.classifyUrl("https://x.com/demo/status/1").kind,"post");assert.equal(core.classifyUrl("https://vt.tiktok.com/ZSdfasdf/").kind,"post");assert.equal(core.classifyUrl("https://www.tiktok.com/t/ZT892qwe/").kind,"post");assert.equal(core.classifyUrl("https://www.threads.net/t/C12345/").kind,"post");});
test("rejects deceptive hosts",()=>assert.equal(core.platformOf("https://instagram.com.evil.test/p/1"),null));
test("normalizes profile share URL",()=>assert.equal(core.canonicalProfileUrl("instagram","https://instagram.com/demo?igsh=x"),"https://instagram.com/demo/"));
test("sanitizes provider URLs",()=>assert.equal(core.sanitizeProviderError(new Error("failed https://example.com/a?token=abc")).message.includes("example.com"),false));
test("selects progressive h264 mp4 with audio",()=>{const selected=pickBest([{url:"a",ext:"webm",height:2160,vcodec:"av01",acodec:"opus"},{url:"b",ext:"mp4",height:1080,vcodec:"avc1.4d",acodec:"mp4a"}],"auto");assert.equal(selected.url,"b")});
test("auto mode excludes video-only formats",()=>assert.equal(pickBest([{url:"a",ext:"mp4",vcodec:"avc1",acodec:"none"}],"auto"),null));
test("cobalt audio-shaped result keeps audio extension",()=>{const result=core.validateResult({platform:"x",provider:"cobalt",items:[{type:"audio",url:"https://video.twimg.com/a.m4a",filename:"a.m4a"}]},{mode:"audio"});core.applyDownloadFilenames(result);assert.equal(result.items[0].filename,"tkangambl.m4a")});
test("result validation removes video without audio in auto",()=>assert.throws(()=>core.validateResult({platform:"x",items:[{type:"video",url:"https://video.twimg.com/a.mp4",filename:"a.mp4",hasAudio:false}]},{mode:"auto"})));test("mime mapping covers mkv and avif",()=>{assert.equal(core.mimeFromFilename("x.mkv"),"video/x-matroska");assert.equal(core.mimeFromFilename("x.avif"),"image/avif")});test("download allowlist rejects arbitrary and HTTP URLs",()=>{assert.equal(download.allowedMediaUrl("https://video.twimg.com/a.mp4"),true);assert.equal(download.allowedMediaUrl("https://evil.test/a.mp4"),false);assert.equal(download.allowedMediaUrl("http://video.twimg.com/a.mp4"),false)});test("signed tokens round trip",()=>{process.env.DOWNLOAD_TOKEN_SECRET="test-secret";const t=core.signDownloadToken({url:"https://video.twimg.com/a.mp4",filename:"a.mp4"},60);assert.deepEqual(core.verifyDownloadToken(t),{url:"https://video.twimg.com/a.mp4",filename:"a.mp4"});delete process.env.DOWNLOAD_TOKEN_SECRET});test("parallel provider race returns first valid result",async()=>{const got=await raceProviders([{name:"slow",run:()=>new Promise(r=>setTimeout(()=>r({platform:"x",items:[{type:"image",url:"https://pbs.twimg.com/a.jpg",filename:"a.jpg"}]}),40))},{name:"fast",run:async()=>({platform:"x",items:[{type:"image",url:"https://pbs.twimg.com/b.jpg",filename:"b.jpg"}]})}],"auto");assert.equal(got.provider,"fast")});test("yt-dlp normalization uses compatible format",()=>{const result=normalizeYtdlp({title:"Demo",formats:[{url:"a",ext:"mp4",height:720,vcodec:"avc1",acodec:"mp4a"}]},{platform:"facebook",kind:"post",handle:""},"auto");assert.equal(result.items[0].hasAudio,true)});

test("safeFilename doesn't over-truncate",()=>assert.equal(core.safeFilename("a".repeat(100)).length, 96));
